### ISSUE TITLE
Plugin crashes upon connecting "Testing purposes" integration

### ISSUE THREAD

**Issue by nffaruk** [bertbert72/galaxy-integration-geforcenow#3]
I know it's been a few years, but unfortunately this doesn't seem to work with GOG Galaxy Client 2.0.73.27 - Beta

**Comment by bertbert72** [comment]
Are you actually using the integration?  I abandoned it when it became clear that GOG themselves had given up on integrations from Galaxy Client.  All the requests for adding platforms are sitting in an issue being ignored since their developer left.  It's been over 2 years since the last update.

Personally I've switched over to PlayNite with the GeforceNow plugin.  That effectively does what I was trying to achieve in Galaxy.

**Comment by nffaruk** [comment]
I never got to use it but came across a mention of it. It's understandable that you've abandoned it due to their lack of support - a shame considering the resources they had at one point. Thanks for pointing out PlayNite, I'll give it a try!
